trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: RunRobotTests
  displayName: 'Run Robot Framework Tests'
  steps:
  - script: |
      # Install Robot Framework and dependencies
      pip install robotframework robotframework-seleniumlibrary
      
      # Install any additional dependencies from requirements.txt
      pip install -r requirements.txt

      # Install Chrome, Firefox, and Edge browsers
      apt-get update && apt-get install -y \
        chromium-browser \
        firefox \
        microsoft-edge-dev

      # Install Chrome WebDriver
      LATEST_CHROME_DRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
      curl -s -o /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_CHROME_DRIVER_VERSION/chromedriver_linux64.zip
      unzip /tmp/chromedriver.zip -d /usr/local/bin/

      # Install Firefox WebDriver (geckodriver)
      LATEST_GECKO_DRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4)
      curl -s -o /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/$LATEST_GECKO_DRIVER_VERSION/geckodriver-$LATEST_GECKO_DRIVER_VERSION-linux64.tar.gz
      tar -xzf /tmp/geckodriver.tar.gz -C /usr/local/bin/

      # Install Edge WebDriver
      curl -s -o /tmp/msedgedriver.zip https://msedgedriver.azureedge.net/LATEST_RELEASE_92/msedgedriver_linux64.zip
      unzip /tmp/msedgedriver.zip -d /usr/local/bin/

      # Run Robot Framework tests
      robot your_test_suite.robot
    displayName: 'Install Dependencies and Run Tests'
